### PR TITLE
Fix cache invalidation

### PR DESCRIPTION
**Pull request by jgpaiva**
This PR should be applied to our branch to fix a problem with cache invalidation: graphite-project#945

Closes Issue #1

### CODE REVIEW

**Comment by tjsousa** [comment]
This is awesome! Can you shed a bit more detail on what the problem was and how does this fix it?

Thanks!

**Comment by jgpaiva** [comment]
I omitted that because the commit messages include _lots_ of details. But basically the problem is that when graphite loaded data from the cache, it still inserted the data again and reset the timeout for invalidation. This caused the cache to never be invalidated if there were new queries retrieving the same data. It's important to notice that with this cache in place, even after the fix, it may still take up to 1minute for new data to be shown on graphite.

**Comment by tjsousa** [comment]
Yeah, I digged that commit message :heart: :blue_heart: :yellow_heart: 

So, theoretically this can lead to increased load on our Graphite servers, right? I'm going to ping @punnie on what can be done to avoid performance problems in production.

**Comment by jgpaiva** [comment]
As spoken IRL, this is good to be deployed in staging, so I'm going to go ahead and merge it.

**Pull request merged**
